version: '2'
name: media-stack
services:

  ## Uncomment to enable transmission as bittorrent client. ##
  ## Keep one of qbittorrent or transmission ##
  # transmission:
  #   container_name: transmission
  #   image: lscr.io/linuxserver/transmission:3.00-r5-ls127
  #   networks:
  #     - mynetwork
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=UTC
  #     - USER=admin
  #     - PASS=nimdatx
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   volumes:
  #     - tx-config:/config
  #     - torrent-downloads:/downloads
  #     - tx-watch:/watch
  #   restart: "unless-stopped"

  ## Comment qbittorrent service, if transmission is enabled. ##
  ## Default credentials - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:4.4.3.1-r1-ls209
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:4.1.0.6175-ls146
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.8.1507-ls150
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:v0.20.1426-ls74
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.1-1-ls171
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 8920:8920
    restart: unless-stopped

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  jellyfin-config:
  qbittorrent-config:
  ## If transmission is enabled, Uncomment below volumes ##
  # tx-config:
  # tx-watch:

networks:
  mynetwork:
    external: true